name = "Ergo-L-G"
name8 = "ergolg"
locale = "fr"
variant = "ergol_g"
description = "French (Ergo-L) (G)"
url = "https://github.com/gagbo/layouts"
author = "Nuclear Squid"
geometry = "ERGO"
version = "0.6.1"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ ! „ │ @ “ │ # ” │ $ ¢ │ % ‰ ┃ ^   │ &   │ *   │ (   │ )   ┃ _ – ┆ + ± ┆
┆ `   ┃ 1 ¬ │ 2 « │ 3 » │ 4 £ │ 5 € ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ W   │ O   │ D   │ G   ┃ B   │ F   │ L   │*¨   │ K   ┃ {   ┆ }   ┆
·     ┃   æ │     │   œ │   ô │     ┃     │   µ │     │** ` │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ E   │ T   │ X   ┃ :   │ N   │ R   │ I   │ U   ┃ "   ┆ |   ┆
·     ┃   à │   é │   è │   ê │     ┃ . … │   ñ │   î │   û │   ù ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ Z   │ M   │ ?   │ C   │ V   ┃ J   │ P   │ H   │ Y   │ ; • ┃           ·
┆ <   ┃   â │   ß │ - — │   ç │     ┃     │     │     │     │ , · ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │  *µ │     │  *¤ │   ‰ ┃  *^ │  *ˇ │   × │  *´ │     ┃     ┆     ┆
·     ┃   1 │   [ │   ] │   $ │   % ┃   ^ │   & │   * │   ' │   0 ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ⁽ │   ⁾ │     │   ≠ ┃   ± │   — │   ≤ │   ≥ │  *¨ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   + │   - │   < │   > │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *` │   ¦ │   – │   ÷ ┃     │     │  *¸ │   ¬ │     ┃           ·
┆     ┃   ~ │   ` │   | │   _ │   / ┃   \ │   @ │   # │   ! │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift =       "\u202f"  # NARROW NO-BREAK SPACE
altgr =       "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
