name = "Ergo-L VX mod"
name8 = "ergol-vx"
locale = "fr"
variant = "ergol-vx"
description = "French (Ergo-L VX mod)"
url = "https://github.com/gagbo/layouts"
geometry = "ERGO"
version = "0.5.1"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ ! „ │ @ “ │ # ” │ $ ¢ │ % ‰ ┃ ^   │ &   │ *   │ (   │ )   ┃ _ – ┆ + ± ┆
┆ `   ┃ 1 ¬ │ 2 « │ 3 » │ 4 £ │ 5 € ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ G   │ O   │ W   │ K   ┃ B   │ M   │*¨   │ L   │ F   ┃ {   ┆ }   ┆
·     ┃   æ │  *µ │   œ │   ô │     ┃     │   µ │** ` │     │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ E   │ T   │ D   ┃ P   │ N   │ I   │ R   │ U   ┃ "   ┆ |   ┆
·     ┃   à │   é │   è │   ê │  *ˇ ┃  *^ │   ñ │   î │   û │   ù ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ X   │ V   │ ?   │ C   │ Z   ┃ J   │ H   │ ; • │ :   │ Y   ┃           ·
┆ <   ┃   â │   ß │ - — │   ç │     ┃  *¤ │     │ , · │ . … │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │   ‰ ┃  *^ │     │   × │  *´ │     ┃     ┆     ┆
·     ┃   1 │   [ │   ] │   $ │   % ┃   ^ │   & │   * │   ' │   0 ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ⁽ │   ⁾ │     │   ≠ ┃   ± │   — │   ≤ │   ≥ │  *¨ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   + │   - │   < │   > │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *` │   ¦ │   – │   ÷ ┃     │     │  *¸ │   ¬ │     ┃           ·
┆     ┃   ~ │   ` │   | │   _ │   / ┃   \ │   @ │   # │   ! │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift =       "\u202f"  # NARROW NO-BREAK SPACE
altgr =       "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk =         "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift =   "\u2019"  # RIGHT SINGLE QUOTATION MARK
