name = "Grenough"
name8 = "grenough"
locale = "fr"
variant = "grenough"
description = "French (Grenough)"
url = "https://github.com/gagbo/layouts"
author = "Gerry Agbobada"
geometry = "ERGO"
version = "0.1.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ ! „ │ @ “ │ # ” │ $ ¢ │ % ‰ ┃ ^   │ &   │ *   │ (   │ )   ┃ _ – ┆ + ± ┆
┆ `   ┃ 1 ¬ │ 2 « │ 3 » │ 4 £ │ 5 € ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ Y   │ O   │ F   │ B   ┃ G   │ D   │ L   │ :   │ *¨  ┃ {   ┆ }   ┆
·     ┃   æ │     │   œ │   ô │     ┃     │   µ │     │ . … │** ` ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ I   │ E   │ N   │ X   ┃ P   │ T   │ S   │ R   │ U   ┃ "   ┆ |   ┆
·     ┃   à │   é │   è │   ñ │     ┃     │     │   î │   û │   ù ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ Z   │ J   │ ?   │ H   │ V   ┃ K   │ C   │ M   │ W   │ ; • ┃           ·
┆ <   ┃   â │   ß │ - — │   ê │     ┃     │   ç │     │     │ , · ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │  *µ │     │  *¤ │   ‰ ┃  *^ │  *ˇ │   × │  *´ │     ┃     ┆     ┆
·     ┃   1 │   [ │   ] │   $ │   % ┃   ^ │   & │   * │   ' │   0 ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ⁽ │   ⁾ │     │   ≠ ┃   ± │   — │   ≤ │   ≥ │  *¨ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   + │   - │   < │   > │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *` │   ¦ │   – │   ÷ ┃     │     │  *¸ │   ¬ │     ┃           ·
┆     ┃   ~ │   ` │   | │   _ │   / ┃   \ │   @ │   # │   ! │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift =       "\u202f"  # NARROW NO-BREAK SPACE
altgr =       "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
