name= "optimot"
description= "French Bépo-style layout"
url= "https://bépoète.fr/optimot"
geometry= "ANSI"

full='''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│ €   │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │ _   │ %   ┃ ⌫        ┃
│ $ £ │ « “ │ » ” │ " „ │ -   │ + ± │ * × │ / \ │ = ≠ │ ( [ │ ) ] │ @   │ # ° ┃          ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┯━━━━━━━┩
┃        ┃ À   │ J   │ O   │ É   │ B   │ F   │ D   │ L   │ ?   │ Q   │ X   │ Ç   │ Z     │
┃ ↹      ┃   < │   > │   œ │  *´ │   — │     │   { │   } │ ’   │     │   | │     │       │
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┲━━━━┷━━━━━━━┪
┃         ┃ A   │ I   │ E   │ U   │ ;   │ P   │ T   │ S   │ R   │ N   │ !   ┃            ┃
┃ ⇬       ┃   æ │     │     │   ù │ , – │     │   & │     │     │  *~ │*^*¨ ┃ ⏎          ┃
┣━━━━━━━━━┻━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┻━━━━━━━━━━━━┫
┃            ┃ K   │ Y   │ È   │ :   │ W   │ G   │ C   │ M   │ H   │ V   ┃               ┃
┃ ⇧          ┃     │     │  *` │ . … │   • │  *µ │  *¸ │     │     │     ┃ ⇧             ┃
┣━━━━━━━┳━━━━┻━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ Alt   ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

[spacebar]
  shift=       "\u202f"  # NARROW NO-BREAK SPACE
  altgr=       "\u005f"  # LOW LINE
  altgr_shift= "\u00a0"  # NO-BREAK SPACE
