# SPDX-FileCopyrightText: 2023 Gerry Agbobada <git@gagbo.net>
#
# SPDX-License-Identifier: MIT

on: [push]
env:
  python-version: "3.10"
permissions:
  contents: write

name: Build Layouts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build layouts
        run: |
          kalamine layouts/*.toml
      - name: Upload windows layouts
        uses: actions/upload-artifact@v3
        with:
          name: layouts-windows
          path: |
            dist/*.klc
            dist/*.json
      - name: Upload linux layouts
        uses: actions/upload-artifact@v3
        with:
          name: layouts-linux
          path: |
            dist/*.xkb
            dist/*.json
      - name: Upload MacOS layouts
        uses: actions/upload-artifact@v3
        with:
          name: layouts-macos
          path: |
            dist/*.keylayout
            dist/*.json

  make-asset:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: layouts-macos
          path: layouts-macos
      - uses: actions/download-artifact@v3
        with:
          name: layouts-windows
          path: layouts-windows
      - uses: actions/download-artifact@v3
        with:
          name: layouts-linux
          path: layouts-linux
      - run: mv layouts-linux/*.json .
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.json
            layouts-windows/*.klc
            layouts-linux/*.xkb
            layouts-macos/*.keylayout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
